### ISSUE TITLE
Broken with cryptography 42

### ISSUE THREAD

**Issue by angelsl** [bdraco/chacha20poly1305-reuseable#34]
**Describe the bug**

cryptography 42 changed the ChaCha20Poly1305 implementation to be Rust-based. The OpenSSL-based backend in `cryptography.hazmat.backends.openssl.backend` no longer supports ChaCha20Poly1305.

**To Reproduce**

```
[angelsl@slarch ~]$ cd /tmp
[angelsl@slarch tmp]$ python3 -m venv venv
[angelsl@slarch tmp]$ source venv/bin/activate
(venv) [angelsl@slarch tmp]$ pip3 install chacha20poly1305-reuseable
Collecting chacha20poly1305-reuseable
  Obtaining dependency information for chacha20poly1305-reuseable from https://files.pythonhosted.org/packages/6f/eb/c6f24c5f3a72277558944ca232b4ac7e5f83585330d8fee5bbf999dd1b57/chacha20poly1305_reuseable-0.12.0-cp311-cp311-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached chacha20poly1305_reuseable-0.12.0-cp311-cp311-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl.metadata (5.3 kB)
Collecting cryptography>=36.0.2 (from chacha20poly1305-reuseable)
  Obtaining dependency information for cryptography>=36.0.2 from https://files.pythonhosted.org/packages/f8/46/2776ca9b602f79633fdf69824b5e18c94f2e0c5f09a94fc69e5b0887c14d/cryptography-42.0.1-cp39-abi3-manylinux_2_28_x86_64.whl.metadata
  Using cached cryptography-42.0.1-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting cffi>=1.12 (from cryptography>=36.0.2->chacha20poly1305-reuseable)
  Obtaining dependency information for cffi>=1.12 from https://files.pythonhosted.org/packages/9b/89/a31c81e36bbb793581d8bba4406a8aac4ba84b2559301c44eef81f4cf5df/cffi-1.16.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached cffi-1.16.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.12->cryptography>=36.0.2->chacha20poly1305-reuseable)
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Using cached chacha20poly1305_reuseable-0.12.0-cp311-cp311-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl (369 kB)
Using cached cryptography-42.0.1-cp39-abi3-manylinux_2_28_x86_64.whl (4.6 MB)
Using cached cffi-1.16.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (464 kB)
Installing collected packages: pycparser, cffi, cryptography, chacha20poly1305-reuseable
Successfully installed cffi-1.16.0 chacha20poly1305-reuseable-0.12.0 cryptography-42.0.1 pycparser-2.21

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
(venv) [angelsl@slarch tmp]$ python3 
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from chacha20poly1305_reuseable import ChaCha20Poly1305Reusable
>>> ChaCha20Poly1305Reusable(ChaCha20Poly1305Reusable.generate_key())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/chacha20poly1305_reuseable/__init__.py", line 82, in chacha20poly1305_reuseable.ChaCha20Poly1305Reusable.__init__
  File "/tmp/venv/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 572, in aead_cipher_supported
    return aead._aead_cipher_supported(self, cipher)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/aead.py", line 22, in _aead_cipher_supported
    cipher_name = _evp_cipher_cipher_name(cipher)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/aead.py", line 66, in _evp_cipher_cipher_name
    assert isinstance(cipher, AESGCM)
AssertionError
>>>
```

**Comment by bdraco** [comment]
Might as well remove the check as it should be supported on all modern versions that newer cryptography supports

**Comment by bdraco** [comment]
@angelsl 0.12.1 published. Please let me know if it solves the issue for you.

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/pull/108956 will get a good test on HA as well
